### ISSUE TITLE
Not all mission variables included in core_mission_inputs

### ISSUE THREAD

**Issue by johnjasa** [OpenMDAO/Aviary#254]
### Description

The variables included in `core_mission_inputs` need to be checked and updated to ensure they include all possible mission variables.

We ran into an issue where a variable used in the ODE (`Aircraft.Wing.INCIDENCE`) was not included but should be. It's only used in the groundroll_ode so I could see it slipping through the cracks. This was specifically for the groundroll phase but there may be other combinations of phases and variables.

### Example

See description

### Aviary Version

0.9.4-dev

**Comment by jkirk5** [comment]
It appears that this is no longer relevant (reworks to the paramport/input var ports have deleted the file with the reference list)
