### ISSUE TITLE
Aviary asks for hydraulic pressure in Lbs/ft^2 but actually needs PSI (FLOPS)

### ISSUE THREAD

**Issue by ChrisPsenica** [OpenMDAO/Aviary#326]
### Description

The hydraulic pressure input unit is listed as Lbs./ft^2. However, the correct units for this as used in Aviary's calculations I believe is actually PSI. This input can be seen, for example, in the file "aircraft_for_bench_FwFm.csv" (line 92). According to the Aviary website the units are Lbs./ft^2 as well but in the FLOPS documentation the units are not specified but rather only given a default value of 3000. A default value of 3000 Lbs./ft^2 would give a hydraulic system pressure of 20.83 PSI which is nonsense considering the application. The plane that is defined in "aircraft_for_bench_FwFm.csv" is set to operate at 20.38 PSI which is incorrect for this size aircraft (especially considering that much smaller planes such as a Cessna operate commonly at 1000-1500 PSI) indicating a discrepancy in the units asked for versus the units actually needed.

### Example

When modeling the King Air 350i, which has a hydraulic system pressure of ~2000 PSI, the optimization reported issues of nan and/or infinite values when the 2000 PSI was converted to Lbs./ft^2. Converting this back to PSI completely eliminated the issue. Unfortunately, I was not able to reproduce the error with the given example problems which indicates that there were other issues with the model tied to the hydraulic pressure. The models on Aviary which use this unit are: large_single_aisle_1, large_single_aisle_2, multi_engine_single_aisle, and N3CC as well as their associated aircraft csv files under the test_aircraft directory. Another instance of these units showing up is under aviary\subsystems\aerodynamics\flops_based\test\data\high_wing_single_aisle.csv. The units for this are set under variable_info\variable_meta_data. I did not find any other files containing this unit for the hydraulic pressure. 

### Aviary Version

0.9.3

**Comment by Kenneth-T-Moore** [comment]
fixed by #328
