### ISSUE TITLE
pkg_resources has been deprecated

### ISSUE THREAD

**Issue by crecine** [OpenMDAO/Aviary#344]
### Description

pkg_resources has been deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources)

### Example

running `import pkg_resources` results in:
`DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html`

### Aviary Version

0.9.4-dev

**Comment by xjjiang** [comment]
Here is the migration guide:

[https://importlib-resources.readthedocs.io/en/latest/migration.html](https://importlib-resources.readthedocs.io/en/latest/migration.html)
