### ISSUE TITLE
Gearbox for Propulsion

### ISSUE THREAD

**Issue by ehariton** [OpenMDAO/Aviary#354]
### Desired capability or behavior.

An optional gearbox component should be added between the motor / turboshaft and the prop. Users should be able to change the gear ratio and that should change the amount the RPM / Torque delivered to the prop at the cost of adding more gearbox mass as the gear ratio gets larger.

Some notes on how this needs to be implemented:
1. Code comments for gearbox in aviary/subsystems/propulsion/motor/model/motor_mission.py need to be moved to a gearbox_mission component
2. Gearbox Mass and supporting RPM calcs to be removed from aviary/subsystems/propulsion/motor/model/motor_premission.py to a gearbox_premission component
3. Aircraft.Engine.Gearbox.GEAR_RATIO constraints in aviary/subsystems/propulsion/motor/motor_builder.py should be moved to a new gearbox_builder.py 
4. TurbopropMission.py and TurbopropModel.py will need to be updated to accept a gearbox component as an input. The build_mission

**Comment by jkirk5** [comment]
Completed with PR #450
