### ISSUE TITLE
Comprehensive Aviary atmospheric component

### ISSUE THREAD

**Issue by jkirk5** [OpenMDAO/Aviary#375]
### Desired capability or behavior.

There are many calculations related purely to flight conditions that are vehicle-agnostic - currently these calculations are only added wherever needed (such as computing Mach from sos and velocity, computing EAS vs. TAS, etc.). A bundled atmosphere component that includes things like dymos' atmosphere component, the `FlightConditions` component, Mach number computation, and others is desired. This should then be added to the api and used throughout the code.

These values are broadly useful to have universally available for all components and should help streamline the code. For example, setting a constraint on EAS for a energy-height mission suddenly becomes really easy if EAS is always computed.

**Comment by xjjiang** [comment]
In `OAS_weight` external subsystem, it uses another atmospheric component called `ambiance`. Is it necessary?

**Comment by jkirk5** [comment]
> In `OAS_weight` external subsystem, it uses another atmospheric component called `ambiance`. Is it necessary?

I don't think that should be part of this new component - `ambiance` is a python package not required for Aviary, as well as only being used for an external subsystem

**Comment by jkirk5** [comment]
_Preserving additional conversation on this topic here:_
DJ:
If I'm not mistaken, GASP flight_conditions.py has a very nice and flexible definition for dynamic pressure. FLOPS based aero has two separate definitions, one each for computed aero and tabular aero.

John:
Thanks DJ, you are indeed correct. Let me try to write out my logic here and you can let me know if it makes sense or not.

We had three ways of computing dynamic pressure in Aviary as you mentioned:
1.) [flight_conditions.py in GASP](https://github.com/OpenMDAO/Aviary/blob/main/aviary/mission/gasp_based/flight_conditions.py)
2.) [computed_aero_group.py had its own version](https://github.com/OpenMDAO/Aviary/blob/main/aviary/subsystems/aerodynamics/flops_based/computed_aero_group.py)
3.) [tabular_aero_group.py had its own which had different inputs](https://github.com/OpenMDAO/Aviary/blob/main/aviary/subsystems/aerodynamics/flops_based/tabular_aero_group.py)

I needed the input/outputs from 2.) above for this new solved aero setup. I could've imported it from computed_aero_group.py, but it seemed slightly more smart to make a new file that could house any commonly used components or methods. So I moved the component to that new file and out of computed_aero_group.py.

Now, the more comprehensive change would be to indeed combine all of these ways of computing dynamic pressure into one component. But that sounds like a very nice add-on PR that's well contained later, when we're not introducing a different aero builder as well. I didn't use the flight_conditions.py implementation here because it has slightly different inputs/outputs than what I needed, and if I'm rewriting that to be more general, I might as well tackle all of them.

Does that make sense? Let me know if it's unclear or if you disagree and we can talk through it.

DJ:
Your explanation makes sense. I can see in my mind a path forward that combines the best of all three, keeping the GASP flight_conditions.py interfaces, but also making the dynamic pressure calculations available as a separate and shared component or set of components. Minimal changes all around, but definitely a slightly different implementation, without actually changing the underlying calculations at all - just (I hope) quality reuse of common code.

IMHO, a follow on PR for that refactor sooner than later would be great.
