### ISSUE TITLE
When a variable override is requested, it should occur even if the output is never used.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/Aviary#513]
### Desired capability or behavior.

In the override_aviary_vars function, line 122, we skip an override if an output is not connected to any downstream inputs in pre-mission. This ignores cases where it might be connected in downstream external subsystems. We should be consistent and override in this case too.

NOTE: There was some reason that we did this. There may be some technical challenges to work through.

### Is your feature request related to a problem? Please describe.

This is, in fact, the reason that the aero_report component is always added to the FLOPS-based aero group -- to create a target connection within pre_mission for aero variables that may be overriden. This component could go away too.

**Comment by xjjiang** [comment]
Example: In the following two cases:

`core_subsystems = get_default_premission_subsystems('GASP', engines)`

`core_subsystems = get_default_premission_subsystems('GASP', engines)[:-1]`

The first one returns `[prop, geom, aero, mass]` and the second returns `[prop, geom, aero]`. Case 1 orverrides
`aircraft:fuselage:wetted_area`, and test 2 does not.
