### ISSUE TITLE
There is no checking on hierarchy variables read in from a csv file.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/Aviary#56]
### Description

If I typo one of the aircraft:* or mission:* hierarchy names, there is no warning or error that I have made a mistake.

Note: the aviary reader is going to see this as a non-hierarchy variable, since you can set any top-level variable in the csv. Maybe we should check the list of var names that get read in, and raise a warning or error for any that are found not to be in the aggregate hiearchy metadata and/or the model.

### Example

"aircraft:wing:mass_scaler" which I could typo as "aircraft:wing:mass_scalar".
It is not a required variable, so I would never know without careful checking versus list_inputs.

### Aviary Version

0.9.2-dev

**Comment by crecine** [comment]
there is already a print if verbosity is high enough:

            if aircraft_values.get_val('verbosity').value >= 2:
                print('Unused:', var_name, var_values, comment)
